name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Change directory
        run: cd language-assistant

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy web.config to output directory
        run: cp web.config ./.next/standalone/
        working-directory: language-assistant

      - name: List files in the standalone directory for verification
        run: ls -la .next/standalone/
        working-directory: language-assistant

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ai-language-instructor"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: language-assistant/.next/standalone
